import { StyleSheet } from "react-native";

export default StyleSheet.create({
  videoContainer: {
    width: "100%",
    height: 200,
    marginBottom: 20,
  },
  video: {
    width: "100%",
    height: "100%",
  },
  searchBar: {
    height: 40,
    borderColor: "#ccc",
    borderWidth: 1,
    borderRadius: 10,
    marginBottom: 20,
    paddingLeft: 10,
  },
  card: {
    backgroundColor: "#fff",
    padding: 15,
    marginBottom: 15,
    borderRadius: 10,
    boxShadow: "0 4px 10px rgba(0, 0, 0, 0.1)",
  },
  cardImage: {
    width: "100%", // Ajusta el ancho al 100% del contenedor
    height: 200, // Altura fija para la imagen
    borderRadius: 10, // Bordes redondeados
    marginBottom: 10, // Espaciado inferior
  },
  cardText: {
    fontSize: 14,
    color: "#333",
    marginBottom: 5,
  },
  fab: {
    position: "absolute",
    right: 20,
    bottom: 20,
    backgroundColor: "teal",
    width: 60,
    height: 60,
    borderRadius: 30,
    justifyContent: "center",
    alignItems: "center",
    elevation: 5, // Android sombra
    zIndex: 9999, // Siempre al frente
    shadowColor: "#000", // iOS sombra
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
  },
  container: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
  formContainer: {
    width: 350,
    height: 500,
    backgroundColor: "#fff",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.35,
    shadowRadius: 15,
    borderRadius: 10,
    paddingHorizontal: 30,
    paddingVertical: 20,
    elevation: 5,
  },
  formContainer2: {
    flex: 1,
    width: 350,
    backgroundColor: "#fff",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.35,
    shadowRadius: 15,
    borderRadius: 10,
    paddingHorizontal: 30,
    paddingVertical: 20,
    elevation: 5,
  },
  formContainer3: {
    height: 500,
    width: 350,
    backgroundColor: "#fff",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.35,
    shadowRadius: 15,
    borderRadius: 10,
    paddingHorizontal: 30,
    paddingVertical: 20,
    elevation: 5,
  },
  title: {
    textAlign: "center",
    marginLeft: 10,
    marginBottom: 30,
    fontSize: 28,
    fontWeight: "800",
    fontFamily: "sans-serif",
  },
  form: {
    width: "100%",
    display: "flex",
    flexDirection: "column",
    gap: 18,
    marginBottom: 15,
  },
  input: {
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#c0c0c0",
    paddingHorizontal: 15,
    paddingVertical: 12,
  },
  linkLabel: {
    textDecorationLine: "underline",
    textAlign: "right",
    color: "#747474",
  },
  formBtn: {
    backgroundColor: "teal",
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderRadius: 20,
    alignItems: "center",
    shadowColor: "#000",
    shadowOpacity: 0.24,
    shadowOffset: { width: 0, height: 3 },
    shadowRadius: 8,
    elevation: 4,
  },
  formBtnDelete: {
    backgroundColor: "red",
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderRadius: 20,
    alignItems: "center",
    shadowColor: "#000",
    shadowOpacity: 0.24,
    shadowOffset: { width: 0, height: 3 },
    shadowRadius: 8,
    elevation: 4,
  },
  btnText: {
    color: "white",
    fontWeight: "bold",
  },
  signUpLabel: {
    fontSize: 10,
    color: "#747474",
    textAlign: "center",
  },
  signUpLink: {
    fontSize: 11,
    color: "teal",
    textDecorationLine: "underline",
    fontWeight: "800",
    textAlign: "center",
  },
  buttonsContainer: {
    width: "100%",
    marginTop: 20,
    gap: 15,
  },
  googleLoginButton: {
    flexDirection: "row",
    borderRadius: 20,
    boxSizing: "border-box",
    paddingTop: 10,
    paddingBottom: 15,
    boxShadow:
      "rgba(0, 0, 0, 0.16) 0px 10px 36px 0px, rgba(0, 0, 0, 0.06) 0px 0px 0px 1px",
    cursor: "pointer",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    fontFamily: "Lucida Sans",
    fontSize: 11,
    gap: 5,
    border: "2px solid #747474",
  },
  googleIcon: {
    fontSize: 18,
    marginRight: 8,
  },
});
